# Generated by Django 4.2.7 on 2023-11-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_inning_match_delete_deliveries_delete_matches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(max_length=50)),
                ('bowling_team', models.CharField(max_length=50)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=50)),
                ('non_striker', models.CharField(max_length=50)),
                ('bowler', models.CharField(max_length=50)),
                ('is_super_over', models.BooleanField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(max_length=30)),
                ('dismissal_kind', models.CharField(max_length=30)),
                ('fielder', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(max_length=50)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=100)),
                ('umpire1', models.CharField(max_length=50)),
                ('umpire2', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Inning',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.matches'),
        ),
    ]
